paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  results: "data/results"
  models: "data/models"

thresholds:
  similarity: 0.8
  deduplication_score: 0.5

database:
  url: "postgresql://postgres:postgres@localhost:5439/itskitto"

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"

field_mappings:
  clinic:
    first_name: "first_name"
    last_name: "last_name"
    phone_number: "phone_number"
    date_of_birth: "date_of_birth"
    email: "email"
    address: "address"

  urgent_care:
    first_name: "first_name"
    last_name: "last_name"
    dob: "date_of_birth"
    phone: "phone_number"
    email: "email"
    address_line: "address"

  hospital:
    first_name: "first_name"
    middle_name: "middle_name"
    last_name: "last_name"
    date_of_birth: "date_of_birth"
    phone_number: "phone_number"
    email_address: "email"
    address: "address"

  physical_therapy:
    full_name: "full_name"
    dob: "date_of_birth"
    contact_phone: "phone_number"
    street_address: "address"

